[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 20_000

[fmt]
tab_width = 2
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
arbitrum_fork = "${ARBITRUM_ONE_FORK}"

[invariant]
runs = 2000
depth = 15
